Optional actions in operation
OasisDEX/oasis-earn-sc pull request #130
Opened 2022-11-25 06:26 UTC by fenris85

Optional actions in operation are marked by passing additional array when creating operation in the OperationRegistry, e.g.:

`[ Action1, Action2, Action3, Actions4]` - actions hashes list
`[false, true, false, false]` - optionality list

In above case `Action2` can be skipped. 

Skipping when forming an operation on FE can be achieved by adding param `skipped = true`. This action still has to exist in operation, but all params can be omitted. It requires only actionHash and `skipped` param.

2022-11-28 09:53 UTC, peculiarity requested changes

2022-11-28 09:53 UTC, peculiarity commented on contracts/core/OperationsRegistry.sol
```
struct Action {
  hash: bytes32,
  isSKippable: bool,
 }
 ```

2022-11-28 09:53 UTC, peculiarity commented on contracts/core/OperationsRegistry.sol
```
struct Operation {
   actions: Action[],
   string: name
}
```

2022-11-28 09:53 UTC, peculiarity commented on contracts/core/OperationsRegistry.sol
> +  function addOperation(string memory name, bytes32[] memory actions, bool[] memory optional) external onlyOwner {
```addOperation(Operation calldata operation) external onlyOwner```

2022-11-28 09:53 UTC, peculiarity commented on test/common/OptionalActions.test.ts
> +const createAction = ActionFactory.create
IMO tests are not written well. 
Let's for example comment out the call

```
// if(!calls[current].skipped) {
//   address target = registry.getServiceAddress(calls[current].targetHash);
//   target.execute(calls[current].callData);
// }
 ```
 Which is in the `OperationExecutor`. These test will pass. 
 I'm not sure what exactly is being test. Also you shouldn't be testing a given contract through proxy calls ( I mean one contract, calling the other contract ) and verifying if the TX is successful.

2022-11-28 09:53 UTC, peculiarity commented on test/common/OptionalActions.test.ts
> +const createAction = ActionFactory.create
Write tests that given `addOperation` and some params ` `getOperation` will return same values.
That will be under `OperationsRegistry.test.ts`
We should have `OperationsExecutor` which must contain logic about testing the login within `executeOp`. 
You can call an action for example that will fire an event and check if the TX contains that event or if state is changed or smth like that. 
We have only integration tests which is not good.

2022-12-01 14:23 UTC, BackToTheCode commented on contracts/core/OperationsRegistry.sol
Kuba mentioned he's already looked into this. And dynamic arrays of structs create issues elsewhere

2022-12-01 14:24 UTC, BackToTheCode commented on test/common/OptionalActions.test.ts
> +const createAction = ActionFactory.create
Broadly agree. I'm going to ask Frank if we can have a ticket for this next sprint.

2022-12-01 14:31 UTC, BackToTheCode approved these changes

2022-12-01 14:31 UTC, merged