Morpho blue init
OasisDEX/oasis-earn-sc pull request #498
Opened 2023-10-18 08:07 UTC by piekczyk

## Ticket URL

Please provide a link to the ticket:

## Description of Changes

Please list the changes introduced by this PR:

- [ ]
- [ ]
- [ ]

## How to Test

Please provide instructions on how to test the changes in this PR:

## PR Definition of Done

Please ensure the following requirements have been met before marking the PR as ready for review:

- [ ] All checks are passing
- [ ] PR is linked to a corresponding ticket
- [ ] PR title is clear and concise
- [ ] Code has been self-reviewed and any fixes or improvements noted (See Code review standards in Notion)
- [ ] Documentation has been updated if necessary

2023-10-18 16:05 UTC, piotrwitek requested changes

2023-10-18 16:22 UTC, piotrwitek commented on packages/dma-library/src/types/ajna/ajna-position.ts
> +export interface BorrowishPosition {
also get rid of IAjnaEarn and instead use IPosition

2023-10-18 16:27 UTC, piotrwitek commented on packages/dma-library/src/types/ajna/ajna-position.ts
> +export class AjnaPosition implements BorrowishPosition {
Isn't it AjnaBorrowMultiplyPosition?

2023-10-25 10:29 UTC, piotrkonowrocki approved these changes

2023-10-25 10:39 UTC, piotrkonowrocki approved these changes

2023-10-25 10:42 UTC, merged